In [2]:
!pip3 install numpy

In [3]:
import numpy as np

In [4]:
arr=np.array([[1,2,3],[4,5,6]])


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

2

In [8]:
arr.shape

(2, 3)

In [9]:
arr.size

6

In [10]:
arr.dtype

dtype('int32')

In [13]:
a=np.array([[1,2,3],[4,5,6]],dtype=float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
b=np.array((2,3,4))
b

array([2, 3, 4])

In [19]:
c=np.zeros([3,4])
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
d=np.ones([3,4], dtype=int)
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
e=np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
f=np.arange(0,30,5)
f

array([ 0,  5, 10, 15, 20, 25])

In [36]:
g=np.linspace(0,30,5)
g

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [37]:
h=np.random.random([2,2])
h

array([[0.22366659, 0.06978264],
       [0.59409406, 0.20717208]])

In [48]:
i=np.array([[2,3,4,6],[4,5,6,2],[7,8,9,20]])
print(i.reshape(2,2,3))

[[[ 2  3  4]
  [ 6  4  5]]

 [[ 6  2  7]
  [ 8  9 20]]]


In [49]:
print(i.reshape(4,3))

[[ 2  3  4]
 [ 6  4  5]
 [ 6  2  7]
 [ 8  9 20]]


In [50]:
print(i.flatten())

[ 2  3  4  6  4  5  6  2  7  8  9 20]


In [55]:
crr=np.array([[2,3,4,21],[-1,2,35,5],[-2,3,-4,5],[2,3,5,4]])
print(crr)


[[ 2  3  4 21]
 [-1  2 35  5]
 [-2  3 -4  5]
 [ 2  3  5  4]]


In [59]:
print(crr[1:4,0:3])

[[-1  2 35]
 [-2  3 -4]
 [ 2  3  5]]


In [57]:
print(crr[1:,:3:2])

[[-1 35]
 [-2 -4]
 [ 2  5]]


In [61]:
cond=crr>0
temp=crr[cond]
print(temp)

[ 2  3  4 21  2 35  5  3  5  2  3  5  4]


In [62]:
drr=np.array([1,2,3,4])

In [70]:
drr+1

array([2, 3, 4, 5])

In [71]:
drr*3

array([ 3,  6,  9, 12])

In [72]:
drr-6

array([-5, -4, -3, -2])

In [73]:
drr**2

array([ 1,  4,  9, 16], dtype=int32)

In [80]:
frr=np.array([[2,3,4],[4,5,6],[1,3,4]])
frr

array([[2, 3, 4],
       [4, 5, 6],
       [1, 3, 4]])

In [81]:
print(frr.T)


[[2 4 1]
 [3 5 3]
 [4 6 4]]


In [88]:
hrr=np.array([[2,3,4],[4,6,9],[1,4,9]])
print(hrr)
print(hrr.max())

[[2 3 4]
 [4 6 9]
 [1 4 9]]
9


In [89]:
print(hrr.max(axis=0))

[4 6 9]


In [90]:
print(hrr.max(axis=1))

[4 9 9]


In [91]:
print(arr.sum())

21


In [94]:
print(hrr.cumsum(axis=0))

[[ 2  3  4]
 [ 6  9 13]
 [ 7 13 22]]


In [96]:
qrr=np.array([[1,2,3],[4,5,6]])
print(qrr)
zrr=np.array([[2,5,3],[7,8,9]])
print(zrr)
print(qrr+zrr)


[[1 2 3]
 [4 5 6]]
[[2 5 3]
 [7 8 9]]
[[ 3  7  6]
 [11 13 15]]


In [99]:
print(qrr-zrr)
print(qrr*zrr)
print(qrr.dot(zrr))



[[-1 -3  0]
 [-3 -3 -3]]
[[ 2 10  9]
 [28 40 54]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [105]:
wrr=np.array([[1,2,3],[4,5,9]])
print(np.sin(wrr))
print(np.exp(wrr))
print(np.sqrt(wrr))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427  0.41211849]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 8.10308393e+03]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 3.        ]]


In [109]:
err=np.array([[1,2,3],[32,4,9]])
print(err)
print(np.sort(err, axis=1))
print(np.sort(err, axis=0))



[[ 1  2  3]
 [32  4  9]]
[[ 1  2  3]
 [ 4  9 32]]
[[ 1  2  3]
 [32  4  9]]


In [111]:
print(np.sort(err, axis=0, kind='mergesort'))


[[ 1  2  3]
 [32  4  9]]


In [120]:
rr=np.array([[1,2,3],[4,5,6]])
kr=np.array([[2,5,3],[7,8,9]])
print(np.hstack((rr,kr)))
print(np.vstack((rr,kr)))

[[1 2 3 2 5 3]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [2 5 3]
 [7 8 9]]


In [119]:
print(np.column_stack((rr,kr)))

[[1 2 3 2 5 3]
 [4 5 6 7 8 9]]


In [121]:
print(np.concatenate((rr,kr)))

[[1 2 3]
 [4 5 6]
 [2 5 3]
 [7 8 9]]


In [127]:
kr=np.array([[2,5,3,3,4],[7,8,9,3,2]])

print(np.hsplit(kr,2))

ValueError: array split does not result in an equal division

In [132]:
kr=np.array([[2,5,3,3,4],[7,8,9,3,2]])
print(np.mean((kr)))
print(np.mean(kr,axis=0))
print(np.median(kr))
print(np.average(kr,weights=w))

4.6
[4.5 6.5 6.  3.  3. ]
3.5


NameError: name 'w' is not defined