# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [ ]:
print(np.__version__)
print(np.show_config())

#### 3. Create a null vector of size 10

In [ ]:
arr=np.zeros([10], dtype=int)
print(arr)

#### 4.  How to find the memory size of any array

In [ ]:
print(arr.nbytes)

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [ ]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [9]:
brr=np.zeros([10])
brr[4]=1
print(brr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [11]:
print(np.arange(10,50,5))

[10 15 20 25 30 35 40 45]


#### 8.  Reverse a vector (first element becomes last)

In [12]:
drr=np.array([2,3,6,5,78,8,6,1])
print(drr[::-1])

[ 1  6  8 78  5  6  3  2]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
print(np.random.randint(0,9,(3,3)))

[[1 0 5]
 [7 6 5]
 [2 4 4]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [19]:
krr=np.array([1,2,0,0,4,0])
print(np.nonzero(krr))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [17]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [20]:
print(np.random.random([3,3,3]))

[[[0.02669176 0.20425268 0.1622622 ]
  [0.47869913 0.82682067 0.11898788]
  [0.76643054 0.00323836 0.94792952]]

 [[0.84627052 0.51929259 0.3836103 ]
  [0.75497036 0.99260736 0.72538272]
  [0.67473999 0.29521039 0.40356213]]

 [[0.58568896 0.52856035 0.68357389]
  [0.17632724 0.25522335 0.41285212]
  [0.53670508 0.65683738 0.37523853]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [6]:
frr=np.random.random([10,10,10])
print(frr)
print(frr.min())
print(frr.max())

[[[3.52029108e-01 8.37390866e-01 5.83459634e-01 5.54390493e-01
   5.26562320e-01 4.73884426e-01 6.26451171e-02 1.93361324e-01
   3.36740564e-01 3.42262510e-01]
  [1.65336611e-01 9.01200181e-01 8.79806386e-01 8.78274750e-01
   2.53130324e-01 2.60263316e-01 5.60767021e-01 1.94224092e-01
   1.43004554e-01 5.72028350e-01]
  [6.03965994e-01 4.11544223e-01 5.68019095e-02 3.85483952e-01
   5.50874570e-01 6.27872395e-01 2.32777475e-01 2.47425920e-01
   1.57782863e-01 4.85620113e-01]
  [2.99308935e-01 9.56899807e-01 2.87331830e-01 8.77767621e-01
   3.10105458e-01 5.78821177e-01 3.05741646e-01 5.31025644e-01
   4.15282587e-01 2.70900934e-01]
  [5.89515453e-02 5.09127434e-01 9.97031286e-01 4.48803326e-02
   6.50971414e-01 2.61947926e-01 5.26059953e-01 4.15116669e-01
   1.56824741e-01 5.76278833e-03]
  [2.96835123e-01 5.17305223e-01 5.95970513e-01 4.10470944e-01
   3.79180484e-01 4.27563748e-01 3.01125750e-01 5.31773061e-01
   1.24301441e-01 4.20789142e-01]
  [8.75515367e-02 1.55239763e-01 3.22377

#### 14. Create a random vector of size 30 and find the mean value

In [8]:
krr=np.random.random([30])
print(krr)
print(np.mean(krr))

[0.79443372 0.13191888 0.45308654 0.7970392  0.39996017 0.30760658
 0.88295574 0.25052799 0.26662515 0.33847566 0.85912859 0.39686103
 0.30117148 0.30955928 0.69652806 0.95802329 0.5243194  0.57320889
 0.99526005 0.27828202 0.60432173 0.07279522 0.7793568  0.98502022
 0.48714943 0.68173687 0.46016877 0.99317586 0.87914285 0.4504657 ]
0.5636101730878306


#### 15. Create a 2d array with 1 on the border and 0 inside

In [22]:
brr=np.ones([6,6])
brr[1:-1,1:-1]=0
print(brr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [31]:
ans = np.ones((5,5))
np.pad(ans,pad_width = 1, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [26]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [28]:
hrr=np.diag([1,2,3,4],-1)
hrr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [29]:
mrr=np.zeros((8,8),dtype=int)
mrr[1::2,::2] = 1
mrr[::2,1::2] = 1
mrr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [30]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)